language: java

addons:
  sonarcloud:
    organization: "welldoer-github"
    token:
      secure: $SONAR_TOKEN  # Set in the settings page of your repository, as a secure variable

cache:
  directories:
    - "$HOME/.gradle"
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"

services:
  - xvfb
  
script:
  - test -n $SONAR_TOKEN && ./gradlew sonarqube

after_failure:
 - cat /home/travis/build/welldoer/JavaBook-DeepIntoSpringBoot/build/reports/tests/test/index.html
