language: java

cache:
  directories:
    - "$HOME/.gradle"
    - "$HOME/.m2/repository"

services:
  - xvfb
  
script:
  - ./gradlew check

after_failure:
 - cat /home/travis/build/welldoer/JavaBook-DeepIntoSpringBoot/build/reports/tests/test/index.html
